# -*- coding: utf-8 -*-
"""Pencil_sketch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/193yVoBcgkq720xc7AGQX11Pd4Dbyth4l
"""

from google.colab.patches import cv2_imshow

import cv2

img = cv2.imread('/content/2019-08-21-14-25-17-424.jpg')
im = cv2.resize(img,(300,300))
cv2_imshow(im)

gr_img = cv2.cvtColor(im,cv2.COLOR_RGB2GRAY)
cv2_imshow(gr_img)

neg_img = cv2.bitwise_not(gr_img)
cv2_imshow(neg_img)

blur = cv2.GaussianBlur(neg_img,(21,21),sigmaX = 0,sigmaY=0)
cv2_imshow(blur)

def dodge(x,y):
  return cv2.divide(x,255-y,scale=256)

fin_img = dodge(gr_img,blur)
cv2_imshow(fin_img)

